### PR TITLE
fix for connection refused on 443 #233

### LINKED ISSUE #233: kubectl get nodes connection refused
I updated my boxes and started to get this error when running kubectl from host:

    error: couldn't read version from server: Get https://172.17.4.101/api: dial tcp 172.17.4.101:443: connection refused

I ssh into c1 and open port 443 in iptables and now I can connect:
    `vagrant ssh c1`
    `sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 443`

### PR DESCRIPTION
**Pull request by scotty-c**
Added the iptable rules to allow connection on port 443 from the local kubectl client

Fixes #233

### CODE REVIEW

**Comment by aaronlevy** [comment]
Thanks for submitting this. I'd still like to try and reproduce the issue before having to add iptables rules (e.g. understand why this would have changed). I'll leave this open for now, but I'd like to still do a bit more digging.

**Comment by scotty-c** [comment]
Good morning Aaron,

No worries. I just added it as a work around to get me up and running.
Thought I just submit a PR in case others were having the same issue.

On Saturday, 13 February 2016, Aaron Levy <notifications@github.com> wrote:

> Thanks for submitting this. I'd still like to try and reproduce the issue
> before having to add iptables rules (e.g. understand why this would have
> changed). I'll leave this open for now, but I'd like to still do a bit more
> digging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/coreos-kubernetes/pull/267#issuecomment-183426119>
> .
>


-- 
Kind regards

Scott Coulton

Sent from Gmail Mobile

**Comment by scotty-c** [comment]
Good morning Aaron,

No worries. I just added it as a work around to get me up and running.
Thought I just submit a PR in case others were

On Saturday, 13 February 2016, Aaron Levy <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Thanks for submitting this. I'd still like to try and reproduce the issue
> before having to add iptables rules (e.g. understand why this would have
> changed). I'll leave this open for now, but I'd like to still do a bit more
> digging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/coreos-kubernetes/pull/267#issuecomment-183426119>
> .
>


-- 
Kind regards

Scott Coulton

Sent from Gmail Mobile

**Comment by philips** [comment]
@scotty-c Do you understand _why_ this is needed? I don't need this on vmware fusion and it works fine so I am super confused.

**Comment by philips** [comment]
I am getting this intermittently on VMWare now. Digging in.

**Comment by scotty-c** [comment]
@philips I am using vagrant 1.8 and virtualbox 5.0.14 with CoreOS Alpha 942.0.0. The reason the rule is needed is that when I ran an nmap on the on c1 port 443 was not open so the ````kubectl```` client was not able to connect. Once the iptables rule was added, the issue was resolved.

**Comment by scotty-c** [comment]
@philips and @aaronlevy I upgraded my CoreOS box to version 'alpha (983.0.0)' The iptables rule no longer works. Do you want to shut this PR and just track this through the issue ?

**Comment by aaronlevy** [comment]
Sure I'll close this issue so we can track in a single place.

**Pull request closed without merging**
