### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by aknuds1**
I think your markdown needs to be formatted in this way, so that list contents aren't treated as code blocks (and contained formatting is applied, e.g. hyperlinks).

### CODE REVIEW

**Comment by robszumski** [comment]
Ha, looks like crap currently:

image

This broken in https://github.com/aknuds1/coreos-kubernetes/commit/9e6b28144a2b99a682423e685f18cf8663e70d06 which was also trying to fix this formatting. The problem lies with differences in the markdown renders between Github and coreos.com, although they should both be Kramdown AFAIK. I'll be sure to preview this on my local machine this time to make sure we fix it once and for all.

**Comment by aknuds1** [comment]
@robszumski How do I preview coreos.com's rendering? On GitHub my changes looked OK.

**Comment by robszumski** [comment]
You can't, I will do that for you! It should match Github rendering about 95%. There are a few edge cases unfortunately.

**Comment by aknuds1** [comment]
@robszumski :( What would be the right formatting in this case? Would be interested in learning.

**Comment by robszumski** [comment]
Checked this out locally, it looks good. The issue was the previous PR used a tab, which gets interpreted as a code block, instead of 4 spaces, as you used, which will nest the content correctly.

**Pull request merged**
