### PR TITLE
all: bump to v1.4.1+coreos.0 / kube-dns-v20

### PR DESCRIPTION
**Pull request by felixbuenemann**
This includes the required addon updates to kube-dns v20 which is
included in K8s 1.4.1.

Changes to the kube-dns rc where taken from:

Bump up addon kube-dns to v20 for graceful termination:
kubernetes/kubernetes#3e55d4d6bd8847791f7119fbd669b5b1d7bc575e

In addition some changes to the health checks that were missed in
previous version bumps were taken from:

Tune down initialDelaySeconds for readinessProbe:
kubernetes/kubernetes#55db76241cf10d0fa943281bd5a8aa1e9c4dc509

Split dns healthcheck into two different urls:
kubernetes/kubernetes#d17cd1a5147ca7feb63b5d841f24527861b02912

Also fixed an accidental version bump regarding rbd docs for
kubelet-wrapper that were changed in the v1.4.0+coreos.0 bump.

I have only manually tested the changes with `kube-aws`.

This PR obsoletes #712.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Rebased on master and fixed a missed replace in the example syntax of `contrib/bump-version.sh`.

**Comment by pbx0** [comment]
@felixbuenemann Thank you for helping out with this! This looks good to me at first look over. I'll give this a test at some point today and merge it after.

**Comment by pbx0** [comment]
@felixbuenemann  LGTM -- I'll merge it when your ready

**Comment by felixbuenemann** [comment]
Should be ready.

**Pull request merged**
