### PR TITLE
Stable channel is supported and default

### PR DESCRIPTION
**Pull request by colhom**
Depends on #523 . the second commit is the content of this PR.

\cc @aaronlevy @cgag @pbx0

### CODE REVIEW

**Comment by cgag** [comment]
Can you remind me why we didn't have stable supported before?

Code LGTM.

**Comment by colhom** [comment]
@cgag we need rkt >= 1.0 for kubelet-wrapper to work.

**Comment by aaronlevy** [comment]
rkt 1.0 has been in stable for a while... but the kubelet-wrapper just made it to stable.

**Comment by aaronlevy** [comment]
Just want to note that we're going to need to use alpha again for supporting rkt+kubernetes (need newer versions of rkt).

**Pull request merged**
