### PR TITLE
kube-aws: golint: use same var for all cluster methods

### PR DESCRIPTION
**Pull request by cgag**
GoLint doesn't like valid() using "cfg" for its receiver when all
the other methods user "c".

### CODE REVIEW

**Comment by colhom** [comment]
@aaronlevy are you OK with de-linting this project?

**Comment by aaronlevy** [comment]
for sure

**Comment by colhom** [comment]
@cgag LGTM pending a rebase

**Comment by aaronlevy** [comment]
ping @colhom @cgag -- what's status on this?

**Comment by cgag** [comment]
Just rebased this, should be good to go.

**Comment by colhom** [comment]
LGTM

**Pull request merged**
