### PR TITLE
Added ICMP Egress for Worker Nodes

### PR DESCRIPTION
**Pull request by ankitforcode**
1. Added ICMP Egress for Worker Nodes 
2. Added Echo Type ICMP For Controller Ingress and Worker Ingress

### CODE REVIEW

**Comment by ankitforcode** [comment]
@aaronlevy Please check now and do the needful.

**Comment by aaronlevy** [comment]
Sorry for the delayed response, I was out of office.

This actually changes existing behavior now. The original intention (as I understood it) was to allow outbound ICMP requests.

This PR now removes inbound "destination unreachable" ICMP requests (type 3), and adds "echo" (type 0) ingress to controllers/workers. And also only allows outbound echo requests from workers.

If this satisfies a particular use-case for you, can you provide some additional details? Otherwise the expected change would be:

- Ingress rules do not change
- Egress rules allow for all ICMP requests

**Comment by ankitforcode** [comment]
@aaronlevy The PR does not remove anything as it is "from port"  -  "to port" action on security group. This PR only adds echo "type 0" to the existing Ingress rules.

**Comment by aaronlevy** [comment]
I may be misunderstanding, but the ToPort/FromPort fields have special meaning when specifying for ICMP.

From: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html

**FromPort:** the start of port range for the TCP and UDP protocols, or an ICMP type number. An ICMP type number of -1 indicates a wildcard (i.e., any ICMP type number).

**ToPort:** The end of port range for the TCP and UDP protocols, or an ICMP code. An ICMP code of -1 indicates a wildcard (i.e., any ICMP code).

The existing ingress rules allowed for a ICMP Type of 3-destination unreachable (FromPort=3) and any ICMP Code (ToPort=-1).

This modifies those rules to only allow ICMP Type 0-echo relpy (FromPort=0) and any ICMP Code (ToPort=-1).

**Comment by aaronlevy** [comment]
Closing due to inactivity. Please let us know if this should be reopened.

**Pull request closed without merging**
