### PR TITLE
Docs: update Calico versions and add calico-policy-controller to api output

### PR DESCRIPTION
**Pull request by pizzarabe**
Update Calico containers from:
`quay.io/calico/node:v0.19.0`-> `quay.io/calico/node:v0.22.0`
and
`calico/kube-policy-controller:v0.2.0` -> `calico/kube-policy-controller:v0.3.0`

also added the `calico-policy-controller-$node` to the api output

### CODE REVIEW

**Comment by pbx0** [comment]
Looks fine to me, thank you for bumping. Lets double check with @tomdee.

**Comment by tomdee** [comment]
Yes, this is a very useful change but I think it should be applied consistently. There are a whole bunch of other references to these versions that should be updated too.

**Comment by colhom** [comment]
Hello Kubernetes Community,

Future work on kube-aws will be moved to [a new dedicated repository](https://github.com/coreos/kube-aws). @mumoshu will be running point on maintaining that repository- please move all issues and PRs over there as soon as you can. We will be halting active development on the AWS portion of this repository in the near future. We will continue to maintain the vagrant single and multi-node distributions in this repository, along with our [hyperkube container image](https://quay.io/coreos/hyperkube) image.

A community announcement to end users will be made once the transition is complete. We at CoreOS ask that those reading this message avoid publicizing/blogging about the transition until the official annoucement has been made to the community in the next week.

The new dedicated kube-aws repository already has the following features merged in:
* Discrete etcd cluster
* HA control plane
* Cluster upgrades
* Node draining/cordoning

If anyone in the Kubernetes community would like to be involved with maintaining this new repository, find @ chom and/or @ mumoshu on the Kubernetes slack in the #sig-aws channel or via direct message.

~CoreOS Infra Team

**Comment by pizzarabe** [comment]
I guess I got them all.

@tomdee @pbx0

**Comment by aaronlevy** [comment]
I'd ask that these changes are squashed into a single commit. Other than that, I'll defer to @tomdee on review / if this should be merged.

**Comment by tomdee** [comment]
Ack, I'll take a look tomorrow.

**Comment by heschlie** [comment]
I believe this has all been updated in https://github.com/coreos/coreos-kubernetes/pull/768

**Pull request closed without merging**
