### PR TITLE
Documentation: add kube-aws users lists

### PR DESCRIPTION
**Pull request by philips**
Based on the things people put in here. https://github.com/coreos/coreos-kubernetes/issues/647

### CODE REVIEW

**Comment by philips** [comment]
LGTY @tombenner @iameli @meonkeys @danielfm

**Comment by tombenner** [comment]
@philips Great, thanks! For Entelo's "Machines count", could you put "Varies greatly depending on workload"? And feel free to add my work email, tom@entelo.com.

Apart from that, 👍!

**Comment by philips** [comment]
Colin we should add CoreOS too ;)

**Comment by iameli** [comment]
@philips Great, thanks. 👍

**Comment by philips** [comment]
merging to get something going.

**Pull request merged**
