### PR TITLE
docs: update to Kubernetes v1.0.6

### PR DESCRIPTION
**Pull request by bcwaldon**
Kubernetes v1.0.6 is ready to rock

### CODE REVIEW

**Comment by polvi** [comment]
nice!

**Comment by aaronlevy** [comment]
LGTM. Should we bump version in coreos-overlay too?

**Comment by bcwaldon** [comment]
@aaronlevy yeah, wouldn't hurt. This is just a bugfix release, so I don't foresee any compat issues.

**Comment by bcwaldon** [comment]
https://github.com/coreos/coreos-overlay/pull/1559

**Pull request merged**
