### PR TITLE
Added Addon Kube-UI to multi-node aws artifacts

### PR DESCRIPTION
**Pull request by ankitforcode**
1. Added Replication Controller for Kube-UI
2. Added Service for Kube-UI
3. Added Addon - Kube-UI to be launched on Controller node with 'kube-aws up' script also changed the cadvisor port from 0 to 4194
4. Changed the cadvisor port from 0 to 4194 to be used with Kube-UI to get the stats from worker nodes
5. Added Port TCP port 4194 for cAdvisor when using KubeUI in render function for kube-aw

### CODE REVIEW

**Comment by ankitforcode** [comment]
@aaronlevy Can you please review

**Comment by aaronlevy** [comment]
Hi @ankitforcode,
Would it be possible to move the cadvisor change into a separate PR? This is something that I've wondered about, and I think it makes sense to use the default behavior (could even just remove the `--cadvisor-port` flag altogether). ref: https://github.com/coreos/coreos-kubernetes/issues/82

As far as the Kube-UI addon, the motivation for this project thus far has been to provide a baseline installation of kubernetes from which users can build on. The DNS addon is part of the initial deployment because it is essentially required for a fully-functioning cluster. But other addons are optional.

In general, the Kubernetes installations based on this repo should pass the upstream conformance tests (another reason the cadvisor port should probably be left at default), but anything running in the cluster beyond that I think should be left up to the user to decide (e.g. UI, Heapster, etc.)

Maybe instead we can add a documentation section for addons which point to the upstream docs / manifests?

**Comment by ankitforcode** [comment]
@aaronlevy Agree.

**Comment by ankitforcode** [comment]
@aaronlevy  I strongly believe that Kube-UI should be the part of the base installation since it provides the base info for the cluster and stats for the worker nodes. As, I can already see there are lots of issues posted on users trying to get the Kube-UI working.

**Comment by aaronlevy** [comment]
I am still leaning toward adding documentation for optional addons, rather than making this decision for the user. For example, we could add something along the lines of:

```
# Deploy Kube-UI addon
> git clone https://github.com/kubernetes/kubernetes
> cd kubernetes && git checkout v1.1.1
> kubectl create -f kubernetes/cluster/addons/kube-ui/.

# Authenticate & expose Kube-UI via proxy:
> kubectl proxy
Starting to serve on 127.0.0.1:8001

# Load kube-UI in browser at: http://127.0.0.1:8001/ui
```

Any thoughts on this @bcwaldon @silas ?

**Comment by bcwaldon** [comment]
I'm strongly for only supporting what is necessary to get a cluster running, then providing documentation & examples for additional components. I don't believe the Kube-UI is required as kubectl provides the same information, albeit via a CLI.

**Comment by aaronlevy** [comment]
Opened an issue for creating documentation for deploying the kube-ui: https://github.com/coreos/coreos-kubernetes/issues/163

Closing this in favor of documenting the steps to deploy kube-ui addon.

**Pull request closed without merging**
