### PR TITLE
Update docs

### LINKED ISSUE #260: Documentation: Code block formatting on website
The code block in the Configure kubectl section is missing line breaks [on this page (Single-Node Kubernetes...) ](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html), although renders OK on [this one](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html).

Possibly because it doesn't have the blank line between?

https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubernetes-on-vagrant-single.md#configure-kubectl vs https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubernetes-on-vagrant.md#configure-kubectl

### PR DESCRIPTION
**Pull request by jrdnull**
Added blank line before code block to fix #260 
Added missing $s to make the sh code blocks more consistent and also missing syntax highlight

### CODE REVIEW

**Comment by robszumski** [comment]
LGTM, thanks for putting it together!

**Comment by jrdnull** [comment]
Hi @robszumski, do the docs need to be regenerated? I'm still seeing the issue mentioned in #260

**Comment by robszumski** [comment]
Whoops, yes, this is normally done for each release, but it seems like one was done 8 days ago but the sync got skipped. I'll make sure it happens.

**Comment by jrdnull** [comment]
Thanks :+1:

**Pull request merged**
