### PR TITLE
Make use of AWS native networking.

### PR DESCRIPTION
**Pull request by eliaslevy**
This pull rips out flannel for multi-node/aws and replaces it with Kubernetes AWS native networking.

### CODE REVIEW

**Comment by ddispaltro** [comment]
I tried to use this, I rebased this change on master, had to up the security groups from 10.2/16 to 10/8 on line https://github.com/coreos/coreos-kubernetes/pull/141/files#diff-da222392c29da368a3a2c580c10576e2R259 to get anything to work.

But the weird thing is I can't seem to get service ip's to work from within their container.  So for instance using heapster

get pods:
```console
NAMESPACE     NAME                  CLUSTER_IP   EXTERNAL_IP   PORT(S)             SELECTOR                AGE
kube-system   heapster              10.3.0.77    <none>        80/TCP              k8s-app=heapster        7h
```

get endpoints:
```console
NAMESPACE     NAME                  ENDPOINTS                     AGE
kube-system   heapster              10.2.1.3:8082                 7h
```

ssh to heapster, use service ip
```console
~ ❯❯❯ kubectl --namespace=kube-system exec heapster-v10-gcvri -it bash
root@heapster-v10-gcvri:/go# curl 10.3.0.77
```
this times out

ssh to heapster, then use endpoint ip
```console
~ ❯❯❯ kubectl --namespace=kube-system exec heapster-v10-gcvri -it bash
root@heapster-v10-gcvri:/go# curl 10.2.1.3:8082
<a href="/validate/">Temporary Redirect</a>.
```

ssh to random container not on same machine
```console
~ ❯❯❯ kubectl exec busybox -it sh
sh: shopt: not found
[ root@busybox:/ ]$ curl 10.3.0.77
<a href="/validate/">Temporary Redirect</a>.
```

Any ideas, I've been tearing my hair out, this is on kube 1.1.2 (latest master from yesterday)

**Comment by eliaslevy** [comment]
The mapping of service IPs to endpoints is the domain of `kube-proxy`.  Have you checked `kube-proxy`'s log? Are you running in `iptables` mode or user mode?

**Comment by ddispaltro** [comment]
`iptables` mode, the relevant logs lines are 

```console
/w/d/kubernetes git:master ❯❯❯ kubectl logs --namespace=kube-system kube-proxy-ip-10-0-0-103.us-west-2.compute.internal|grep heapster                                                                                                                                                                                                                                  ⏎
I1201 10:11:30.922427       1 proxier.go:294] Adding new service "kube-system/heapster:" at 10.3.0.77:80/TCP
I1201 10:13:03.214136       1 proxier.go:352] Setting endpoints for "kube-system/heapster:" to [10.2.1.3:8082]
```

I upped the logging on kube-proxy to --v=2

**Comment by eliaslevy** [comment]
If I am reading the issue you are having correctly, then you are only seeing this problem when attempting to access the service from the same Pod that hosts the server's Endpoint.  Yes?  Which means the traffic should be looping back after being DNATed.

You want to run `iptables-save` to dump the iptables rules and see if you can stop why it may not be working.

**Comment by ddispaltro** [comment]
Yes that is correct.

I don't really fully understand the rules, they look alright though, not sure what's going on.

https://gist.github.com/ddispaltro/46afad76ff2f53aeb778

Heres the snippet from the node that is running heapster.  Note: it works to use service ip's from the host, it's only local to the same pod.

**Comment by ddispaltro** [comment]
Oddly enough, when I put the cbr0 into promisc mode it works.  I decided to post the issue over here kubernetes/kubernetes#18100

**Comment by eliaslevy** [comment]
Interesting.  Looking forward to what the k8s make of it.

**Comment by ddispaltro** [comment]
Okay so basically hairpin needed to be turned on, so I got the new kubelet and ran it.  Then I ran into an issue with the `cbr0` and traffic shaping (tc) I was getting some failed to enable to cbr0 exit code 2 so now I run

```
[Unit]
Description=Set cbr0 to promisc
Requires=sys-devices-virtual-net-cbr0.device
After=sys-devices-virtual-net-cbr0.device

[Service]
TimeoutStartSec=30s
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/tc qdisc add dev cbr0 root handle 1: htb default 30
```

And it all works.

**Comment by eliaslevy** [comment]
Curious. I see no such issue, but I have not yet rebased to the master HEAD and tried that.

**Comment by bcwaldon** [comment]
@eliaslevy could you rebase this on HEAD and test it again?

**Comment by therc** [comment]
The exit code 2 happened to me, too, with K8s 1.1.1 (downloaded manually into /opt) going from beta-835.5.0 to alpha 899.1.0 on AWS (EC2 says it's the 877.1.0 AMI)

**Comment by therc** [comment]
From the other bug:

```
I1229 20:26:38.690613 container_bridge.go:117] Want cbr0 CIDR: 10.128.0.1/24, have cbr0 CIDR: 10.128.0.1/24
I1229 20:26:38.690664 kubelet.go:2274] Shaper is nil, creating
I1229 20:26:38.696311 linux.go:56] Running: tc qdisc delete dev cbr0 root handle 0:
I1229 20:26:38.700850 linux.go:59] Output from tc: RTNETLINK answers: No such file or directory
E1229 20:26:38.700865 kubelet.go:2317] Error configuring cbr0: exit status 2
```

Did anything related change in 4.3.0?

**Comment by eliaslevy** [comment]
@bcwaldon I've merged HEAD on my custom branch, which includes these changes.  Alas, the result is broken as a result of changes in the output of `tc` in the latest versions of CoreOS.  `kubelet` chokes while setting up the `cbr0` bridge when it executed `tc` and received unexpected output.  The Kubernetes issue is kubernetes/kubernetes#19237 opened by @therc as an outgrowth of the kubernetes/kubernetes#18100 issue opened by @ddispaltro. @therc fixed it in kubernetes/kubernetes/pull/19238 and it was cherry picked into the 1.1 branch in kubernetes/kubernetes/pull/19243.  So now we just need to wait for a new 1.1 release to fix it.

**Comment by eliaslevy** [comment]
Looks like I misread kubernetes/kubernetes/pull/19243.  It was closed, not merged. kubernetes/kubernetes/pull/19244 is the replacement, but it is not yet merged against the 1.1 branch.

**Comment by eliaslevy** [comment]
While waiting for the kubelet fix, I reverted my AWS instances to CoreOS Alpha 870.3.0.  Using that version, with my custom branch having merged the the changes in master, the cluster comes up fine.  I tried reproducing the issue @ddispaltro reported and could not.

I will update this branch so it can be merged cleanly.

**Comment by eliaslevy** [comment]
Here it is rebased.

**Comment by aaronlevy** [comment]
I am going to close this, as our plan moving forward (for the near future) is to continue to use flannel for the pod networking layer (rather than using the cloud-provider integration). This reduces the complexity of the tooling across providers. Open to revisit this, but don't have any current plans to make the change.

**Pull request closed without merging**
