### PR TITLE
Documentation: fixed missing white-space et al.

### PR DESCRIPTION
**Pull request by kcyeu**
## Summary
* fixed missing white-space
* added syntax hint ```sh``` to code block

### CODE REVIEW

**Comment by aaronlevy** [comment]
Can we drop the runner.sh? It's nice from a convenience standpoint, but the manual steps are minimal, and I'd like to keep that as documentation for now.

**Comment by kcyeu** [comment]
@aaronlevy Yup, sure. runner.sh is now removed.

**Comment by aaronlevy** [comment]
Can you squash your commits, then we can get this merged.

**Comment by bcwaldon** [comment]
I handled the squash for you. Thanks for the contributions!

**Pull request closed without merging**
