### PR TITLE
missing ports for master

### PR DESCRIPTION
**Pull request by stephanlindauer**
those ports have to be open on the master as well. otherwise things like kube-proxy+dashboard wont work.

### CODE REVIEW

**Comment by aaronlevy** [comment]
@stephanlindauer we should probably document allowing traffic between both masters and workers on the pod network. So maybe updating the ingress rules from both master/worker to state source could be from master & worker?

**Comment by stephanlindauer** [comment]
not 100% sure what you mean. the ports are already mentioned in the `Worker Node Inbound` section. or do you want to add a new table for inboud rules that should be applied to both master and worker nodes?

**Comment by aaronlevy** [comment]
Sorry for the vagueness. We likely also need to allow master->worker pod traffic (and master to master pod traffic). Looks like we're only allowing pod traffic to be sourced from workers.

We mention opening all TCP traffic between worker/master, but not in the case for these UDP ports.

So I think it would just be a change of `source=master & worker` for the flannel rules in both the ingress tables.

**Comment by stephanlindauer** [comment]
ok understood. makes sense. ;) 
i changed the pr accordingly.

**Comment by aaronlevy** [comment]
LGTM, thanks!

**Comment by aaronlevy** [comment]
Oh actually, would you mind squashing into a single commit?

**Comment by stephanlindauer** [comment]
yup. done.

**Pull request merged**
