### PR TITLE
use vxlan backend in aws

### PR DESCRIPTION
**Pull request by spacepluk**

### CODE REVIEW

**Comment by philips** [comment]
yes, there is no reason not to do this AFAIK!

**Comment by spacepluk** [comment]
There's still a problem when you try to reach services through kubectl proxy.

I got it working with some changes in my custom template, but I still need to tweak how kube-aws generates the security groups.   I hope I'll have some time to do that today.

**Comment by spacepluk** [comment]
I put all the changes in a new commit and rebased on top of master.

**Comment by aaronlevy** [comment]
Awesome, thank you @spacepluk! I'll try and get this tested today.

**Comment by aaronlevy** [comment]
@spacepluk Sorry I haven't gotten around to testing your change yet.

There is currently a pretty large re-write of the kube-aws tool that is getting very close and we're trying to get that wrapped up. Once that is in place, this PR will likely need to be modified to fit the new format. Would you mind if we hold off on this for a little bit, assuming that change makes it in soon, then rebase on top of that?

ref: #316

**Comment by spacepluk** [comment]
Sure, no problem!  I saw the big thread about the refactor but I haven't had time to take a look.  It shouldn't be too hard anyways.

**Comment by aaronlevy** [comment]
Hi @spacepluk, so the large refactoring was merged. Would you mind restructuring this change to work on the new codebase?

**Comment by spacepluk** [comment]
hi @aaronlevy, I think this patch is correct but I'm dealing with some urgent stuff right now and I can't test it.  I'll let you know as soon as I do.

**Comment by spacepluk** [comment]
I finally got to test this and everything seems to be working fine :)

**Comment by colhom** [comment]
This passes conformance tests. (coreos-kubernetes-kube-aws-v2 #37)

LGTM

**Comment by colhom** [comment]
Ok, tested this commit rebased on top of master. (job # 38)

LGTM

**Comment by aaronlevy** [comment]
Thanks @spacepluk !

**Pull request merged**
