### PR TITLE
WIP: dont map public IPs

### LINKED ISSUE #535: Option to not assign public IPs for worker nodes
Is it necessary for worker nodes get assigned public IPs? All the subnets created by kube-aws 0.7.1 are currently set to automatically assign public IP address to new instances (MapPublicIpOnLaunch = true). If this is a preference rather than a requirement, could this be a `cluster.yaml` option which changes the flag in `stack-template.json` ?

The controller needs a public/accessible IP of course, and it has the option to assign an EIP one, so no problem there.

```
...
    "{{$subnetLogicalName}}": {
      "Properties": {
        "AvailabilityZone": "{{$subnet.AvailabilityZone}}",
        "CidrBlock": "{{$subnet.InstanceCIDR}}",
        "MapPublicIpOnLaunch": true,
        "Tags": [
          {
            "Key": "KubernetesCluster",  
            "Value": "{{$.ClusterName}}"
          }
        ],
        "VpcId": {{$.VPCRef}}
      },
...
```

### PR DESCRIPTION
**Pull request by pieterlange**
Adds a toggle to stop mapping public IP's for anything in the cluster. (workers, controllers, ELB)

Based against @colhom's `cluster-upgrades` WIP branch and fixes #535 (i think?).

### CODE REVIEW

**Comment by colhom** [comment]
@pieterlange I'm back from vacation! Sorry for the delay, we should be making progress towards getting #608 merged soon!

**Comment by pieterlange** [comment]
This patch is currently broken but i will update the PR when your branch gets merged!

**Comment by gmcquillan** [comment]
I'd still really like to see this change get merged. Should I take a stab at the merge conflicts?

**Comment by gmcquillan** [comment]
https://github.com/pieterlange/coreos-kubernetes/pull/1

**Comment by gmcquillan** [comment]
@pieterlange Oh, there is one lingering problem: 

```
[gmcquillan@quark aws]$ go test $(go list ./... | grep -v '/vendor/')
# github.com/coreos/coreos-kubernetes/multi-node/aws/pkg/tlsutil
pkg/tlsutil/x509.go:72: undefined: Duration90d
```

I have no idea why this changed, but maybe we can just drop this statement block?
```
	if cfg.Duration == time.Hour*0 {
		cfg.Duration = Duration90d
	}
```

**Comment by pieterlange** [comment]
This PR has been merged into https://github.com/coreos/kube-aws

**Pull request closed without merging**
