### PR TITLE
Remove dead link.

### PR DESCRIPTION
**Pull request by gosharplite**

### CODE REVIEW

**Comment by philips** [comment]
@robszumski this should point at Documentation/getting-started.md, right?

**Comment by robszumski** [comment]
For now yes. The link on coreos.com will be live after https://github.com/coreos/coreos-kubernetes/pull/35 lands, and we can replace the link to Github.

**Comment by bcwaldon** [comment]
@robszumski so what's the course of action here for @gosharplite ?

**Comment by robszumski** [comment]
Sounds like we're gonna be able to land all this stuff soon, so hang tight for a few more hours?

**Comment by robszumski** [comment]
https://coreos.com/kubernetes/docs/latest/getting-started.html is now live. Sorry for the trouble!

**Pull request closed without merging**
