### PR TITLE
Docs: bump kubernetes version to 1.6.1 from 1.5.4

### PR DESCRIPTION
**Pull request by ElijahCaine**
This relates to a downstream documentation sync.

We don't want to look like we're behind the times, right?

cc: @joshix @robszumski

### CODE REVIEW

**Comment by robszumski** [comment]
This is fine as long as it works...

**Comment by ElijahCaine** [comment]
@robszumski I tried some of the URLS (a 'random sampling' we'll call it) and everything seemed to work fine.

**Comment by vietwow** [comment]
Hi EijahCaine,

How about kubernetes dashboard version ? Why don't you bump it into v1.6.0 ?

Best Regards,
VietNC

**Comment by joshix** [comment]
@ElijahCaine Please update dashboard versions in deploy-addons.md as well (sorry about the erroneous reviews)

**Comment by ElijahCaine** [comment]
@joshix Bumped.

**Comment by joshix** [comment]
@ElijahCaine LGTM - why is dashboard one dot version back, tho?
@aaronlevy PTAL

**Comment by ElijahCaine** [comment]
@joshix It's one version back because https://github.com/kubernetes/dashboard/releases/tag/v1.6.0 is the latest tag.

**Comment by ElijahCaine** [comment]
Jumped the gun on this one. Closing until we *actually* bump to 1.6.1.

**Pull request closed without merging**
