### PR TITLE
fixes cluster not starting post kube-aws up

### PR DESCRIPTION
**Pull request by johnt337**
v0.8.0 would not start until I added the requires.

### CODE REVIEW

**Comment by iwarp** [comment]
Thanks just tested this and cluster is starting perfectly

**Comment by cgag** [comment]
Ugh.  We removed this in an attempt to fix this issue, but it looks like it didn't help. https://github.com/coreos/coreos-kubernetes/issues/545.  

cc @colhom.

**Comment by robszumski** [comment]
Can confirm that this issue hit my existing cluster. Upon reboot/OS update, the kubelet's depdency chain failed and didn't restart it.

**Comment by colhom** [comment]
The issue has to do with retry limits of one or more of the various __dependencies__ of `kubelet.service`. The way to fix this is go through all service dependencies and make sure each is allowed to retry for a very long time / ad infinitum.

**Comment by johnt337** [comment]
@colhom thanks, i'll give that a go when I have a few cycles. Should I close this pull request in that case?

**Comment by colhom** [comment]
@johnt337 I'll close it out here. When do you think you'll have that PR up?

**Comment by johnt337** [comment]
@colhom if it's still open I'll try and take a look this weekend.

**Comment by robszumski** [comment]
There is a lot of background on (what I believe is) the issue at https://github.com/coreos/coreos-kubernetes/issues/545

**Comment by johnt337** [comment]
Sorry so just getting around to looking into this again.
I see that by default /usr/lib64/systemd/system/flanneld.service is set to `type=notify` and it contains a `--set-env=NOTIFY_SOCKET=/run/systemd/notify \` in it's ExecStart.

Should it be a matter of `Wants=docker.service` to maintain start order during boot time?

**Pull request closed without merging**
