### PR TITLE
kube-aws: add ECR policies to IAMRoleWorker

### PR DESCRIPTION
**Pull request by spacepluk**

### CODE REVIEW

**Comment by spacepluk** [comment]
Fixes #381

**Comment by colhom** [comment]
@spacepluk my concern here is that deploying a kube-aws cluster does not _imply_ a need for the instances to have IAM access to ECR images on that AWS account. Maybe this should be configurable, and default to no IAM access?

**Comment by valichek** [comment]
@spacepluk the list of policies is not full, here is suggested policies http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry, @colhom kubernetes supports ECR by default. So why not to configure ECR from the box?

**Comment by spacepluk** [comment]
Sorry, I completely missed these comments.

@colhom that's a good point but I'd say it makes sense to support it by default.

@valichek thanks, I'll update the patch.

**Comment by yuvipanda** [comment]
It would be awesome to have this merged :D

**Comment by colhom** [comment]
Here is a link to the [docs](http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry#using-aws-ec2-container-registry) for the ECR-K8s integration @valichek was referring to.

Given that this integration exists, I've been convinced. Thanks everyone!

**Pull request merged**
